[package]
name = "cczu-webvpn-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
once_cell = "*"
scraper = "*"
base64 = "*"
reqwest = { version = "*", features = [
    "cookies",
    "multipart",
    "native-tls-vendored",
] }
tokio = { version = "*", features = ["full"] }
aes = "*"
cbc = "*"
urlencoding = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
reqwest_cookie_store = "*"
